### ISSUE TITLE
memoized layer_mapbox()

### ISSUE THREAD

**Issue by MilesMcBain** [anthonynorth/snapbox#2]
A cool feature for the `layer_mapbox()` could be memoisation. Whether that is the whole function or perhaps just the internal call to `static_map()`. You can freely iterate on your map in dev, whilst making only 1 mapbox static image request.

https://github.com/r-lib/memoise

**Comment by anthonynorth** [comment]
We really only need to memoise the `get_map_image()`.

**Comment by MilesMcBain** [comment]
pushed a commit that added this
