### ISSUE TITLE
should get_static_map take a buffer arg?

### ISSUE THREAD

**Issue by MilesMcBain** [anthonynorth/snapbox#4]
At the moment if you pass it a single point or something lies along either x or y axis, the aspect ratio calculation will fail.

In this case it might be nice to be able to direct users to a `buffer` arg in web mercator meters.

It would also be nice in general for mapping data. As we've seen, things look good with a bit of space around and not running right to the edge.

**Comment by anthonynorth** [comment]
This is fine. Should we buffer the area before or after projection? This changes what the buffer units represent.

We will also need to be clear that buffering will be uniform and will distort the input aspect ratio (unless it's already square).

**Comment by MilesMcBain** [comment]
I think it should be after projection so the buffer affects as directly as possible on what you see in the end product. That way you can try a few iterations and they should mostly change as you expect. I was mucking around with buffering lon lat and observing the change in mercator earlier and the distortion gets quite wild at statewide level.

**Comment by MilesMcBain** [comment]
pushed a commit that added this
